[package]
name = "parsefile"
version = "0.1.0"
authors = ["xuechenwang <xuechenwang@cienet.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap
# https://docs.rs/clap/2.33.0/clap/
clap = "~2.27.0"
