[package]
name = "echo_server"
version = "0.1.0"
authors = ["zenanswer <zenanswer@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-slice = "0.1.4"
